### PR TITLE
Chat App CSS Illustration

### PR DESCRIPTION
**Pull request by amos-kibet**
- Style card according to design
- Add required images
- Add source code link

### CODE REVIEW

**Review by almirsarajcic — CHANGES_REQUESTED** [review]
Images are missing because of incorrect path.

**Comment by amos-kibet** [comment]
> 

All images are available, and tests are passing. @almirsarajcic which images are you seeing missing?

**Review by almirsarajcic — APPROVED** [review]
Now it looks fine.
Weird, it might have been a bug with chromedriver or something like that.

**Comment by amos-kibet** [comment]
No worries, thanks.

**Comment by amos-kibet** [comment]
Just reopened it, not sure if it still passes the checks

**Review by almirsarajcic — CHANGES_REQUESTED** [review]
Tests are failing.

**Comment by amos-kibet** [comment]
I'll probably close this PR and create a fresh one. I lost these files when I deleted this fork

**Pull request closed without merging**
