### PR TITLE
Chat app css illustration

### PR DESCRIPTION
**Pull request by jrowah**
Edits index file to achieve solution to challenge.
Desktop Design:
image

Mobile Design:

https://github.com/optimumBA/frontend_mentor_challenges/assets/76947107/14b84824-aba4-4986-b11e-bc73a55beda6

### CODE REVIEW

**Review by almirsarajcic — CHANGES_REQUESTED** [review]
Doesn't match the proposed design (colors). Also, extra images.

**Review by almirsarajcic — CHANGES_REQUESTED** [review]
There are still some minor differences between the proposed design and the screenshots (phone size and colors). Also, extra images like in the other PRs.

**Review by almirsarajcic — CHANGES_REQUESTED** [review]
Still some differences


design

chat_app_css_illustration-desktop
screenshot

**Review by almirsarajcic — CHANGES_REQUESTED** [review]
Now there are more differences. The text input is not in its place.

**Comment by jrowah** [comment]
> Now there are more differences. The text input is not in its place.
I have seen that under artefacts, fixing right now.

**Review by almirsarajcic — APPROVED** [review]
Could be better, but let's move on.

**Pull request closed without merging**
