### PR TITLE
Stats preview card component

### PR DESCRIPTION
**Pull request by jrowah**
Solution to the Stats preview card component challenge.
Desktop Design:
image

Mobile Design:

https://github.com/optimumBA/frontend_mentor_challenges/assets/76947107/849e07f6-7f9c-4c2f-b21e-eeffb35c3474

### CODE REVIEW

**Review by almirsarajcic — CHANGES_REQUESTED** [review]
There's a difference between screenshots and the proposed design (check the padding inside the box). Also, you've added some unnecessary images.

**Review by almirsarajcic — CHANGES_REQUESTED** [review]
There are still unnecessary icons and padding is not fixed in the desktop variant. Check screenshots made during the tests (`Checks` -> `Artifacts`).

**Review by almirsarajcic — CHANGES_REQUESTED** [review]
Desktop variant dcreenshots doesn't match the proposed design.

stats_preview_card_component-desktop
screenshot


design

**Comment by jrowah** [comment]
I am not sure why this looks different on your side. 
Here is the screenshot generated on my files after running the tests.
image
More changes I make now deviate from that. Would you help me how to handle this situation?

**Comment by almirsarajcic** [comment]
> I am not sure why this looks different on your side.
> Here is the screenshot generated on my files after running the tests.
> image
> More changes I make now deviate from that. Would you help me how to handle this situation?

It's not my side. That was a screenshot generated in GitHub Actions. You can check it under `Checks` -> `Artifacts`.
Even on your side, the font doesn't match the design.

**Comment by jrowah** [comment]
I have checked the Artifacts and seen the difference. Working on it now.

**Review by almirsarajcic — APPROVED** [review]
Good job 👍

**Pull request closed without merging**
